import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Hero from './components/Hero';
import PhotoGrid from './components/PhotoGrid';
import ImageKit from 'imagekit';
import { GetStaticProps } from 'next';

type Props = {
  result: any;
};

const Home: React.FC<Props> = ({ result }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <PhotoGrid pictures={result} />
      </main>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  var imagekit = new ImageKit({
    publicKey: process.env.NEXT_PUBLIC_IK_PUBLIC_KEY || '',
    privateKey: process.env.IK_PRIVATE_KEY || '',
    urlEndpoint: process.env.NEXT_PUBLIC_IK_URL_ENDPOINT || '',
  });

  const result = await imagekit.listFiles({
    skip: 0,
    limit: 100,
  });
  return { props: { result } };
};
